# hexo-theme-miho
# https://github.com/wongminho/hexo-theme-miho

# Favicon of your site | 网站icon
favicon: /favicon.icon

# Header

# Keywords of your site | 网站关键字
keywords: TLY,TLY's Blog
# Head headline | 头部标题
header_title: TLY's Blog
# Head description | 头部描述
header_description: 一个热衷于web前端设计的个人网站，分享生活及工作。
# Link to your logo | logo地址
logo: images/logo.png
# Link to your banner_img | 首页banner图地址
banner_img: images/banner.jpg
# Menu setting | 菜单设置
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Title | 标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
menu:
  home:
    title: 首页
    url: /
    target: false
  book:
    title: 分类
    url: /categories
    target: false
  folder-open:
    title: 项目
    url: /project
    target: false
  archive:
    title: 归档
    url: /archives
    target: false
  edit:
    title: 留言
    url: /saying
    target: false
  user:
    title: 关于我
    url: /about
    target: false
# Social setting, use to display social information | 社交设置，用来展示社交信息
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Icon title | 图标标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
social:
  github:
    title: Github
    url: //github.com/tongliping0709
    target: true
  weibo:
    title: weibo 
    url: //weibo.com/tongliping0709
    target: true
  envelope-o:
    title: email
    url: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=fkhOSkhISUhNTT4PD1AdERM"
    target: true
  twitter:
    title: titter
    url: //twitter.com/
    target: true
  #qq:
  #weixin:
  #snapchat:
  #telegram:
  #envelope-o:
  #facebook:
  #google:
  #linkedin:

pro: images/projects.jpg
# project #
project:
  - title: Apple 官网临摹
    data: 2016.3
    img_link: http://o7bkkhiex.bkt.clouddn.com/item-apple.jpg
    arrayVal: jQuery 
    subTitle: 根据美版apple官网临摹 
    direction: 临摹 2016 年三月份 Apple 美版单页面, 临摹的主要目的是练习响应式页面,兼容 Firefox、Chrome、Edge。使用了 HTML5 的 flex 布局,未在IE上测试,实际上作品页面结构比较凌乱,前期也未作好规划,现在看来有很多的不足和改善空间。
    link: https://github.com/th720309/hexo-theme-believe
  - title: Apple 官网临摹
    data: 2016.3
    img_link: http://o7bkkhiex.bkt.clouddn.com/item-apple.jpg
    arrayVal: jQuery 
    subTitle: 根据美版apple官网临摹 
    direction: 临摹 2016 年三月份 Apple 美版单页面, 临摹的主要目的是练习响应式页面,兼容 Firefox、Chrome、Edge。使用了 HTML5 的 flex 布局,未在IE上测试,实际上作品页面结构比较凌乱,前期也未作好规划,现在看来有很多的不足和改善空间。
    link: https://github.com/th720309/hexo-theme-believe


# Content

# Excerpt length | 摘录长度
excerpt_length: 190
# Excerpt link | 摘录链接
excerpt_link: 全文阅读>>
# New window open link | 新窗口打开文章
open_new_link: false
# Article default cover picture，size：350*150 | 文章默认封面图，尺寸：350*150
cover_picture: images/banner.jpg
# Open background particles | 开启背景粒子
open_bg_particle: true
# Open animation in homepage and head | 开启主页及头部动画
open_animation: true

# Article
# 文章末尾添加“本文结束”标记
passage_end_tag:
  enabled: true

# Open toc | 是否开启toc
toc: true
# Open share | 是否开启分享
share: true

# Style customization | 样式定制
style:
  # Main color tone | 主色调

# Reward | 打赏

reward:
  # 0-close, 1-All articles are rewarding, 2-Article's md file has reward:true attribute, only reward
  # 0-关闭, 1-所有文章均有打赏, 2-文章的md文件里有reward:true属性，才有打赏
  status: 1
  # 标题
  title: 多少都行~
  # 微信，关闭设为 false
  wechat: images/wechat_code.jpg
  # 支付宝，关闭设为 false
  alipay: images/alipay_code.jpg

# Comments | 评论

# 畅言，输入appid和appkey
changyan_appid: false
changyan_appkey: false
# 友言，输入id
youyan_id: false
# disqus
disqus: false
# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8zMzU0Mi8xMDA5OA==

# Analytics | 分析
# 站长分析，输入站点id
cnzz_analytics: false
# 百度分析，输入key值
baidu_analytics: false
# google analytics | google分析
google_analytics: false

# Footer

# Access statistics | “不蒜子”访问量统计
access_counter:
  on: true
  site_uv: 访用户数：
  site_pv: 访问量：

# Copyright Information | 版权信息
copyright: 2018 TLY
